# Generated by Django 3.0.14 on 2023-05-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_info',
            name='SignaturPicture',
        ),
    ]
