# Generated by Django 3.0.14 on 2023-05-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_account_info_signaturpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_info',
            name='SignaturPicture',
            field=models.ImageField(max_length=250, null=True, upload_to=''),
        ),
    ]
