# Generated by Django 3.0.14 on 2023-05-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_account_info_signaturpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawdeposit',
            name='Status',
            field=models.CharField(default='incomplete', max_length=250),
        ),
    ]
