# Generated by Django 3.0.14 on 2023-05-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_withdrawdeposit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(default='incomplete', max_length=250),
        ),
        migrations.AddField(
            model_name='transfer',
            name='status',
            field=models.CharField(default='incomplete', max_length=250),
        ),
    ]
