# Generated by Django 3.0.14 on 2023-06-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230514_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default='Active', max_length=250),
        ),
    ]
